### ISSUE TITLE
NullPointerException while applying water animation task

### ISSUE THREAD

**Issue by ceskyDJ** [ceskyDJ/NetherWater#11]
```
[23:25:40] [Server thread/WARN]: [NetherWater] Task #28 for NetherWater v1.12 generated an exception
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:221) ~[?:?]
        at cz.ceskydj.netherwater.database.DB.createBlockFromResultSet(DB.java:258) ~[?:?]
        at cz.ceskydj.netherwater.database.DB.getAllWaterBlocks(DB.java:221) ~[?:?]
        at cz.ceskydj.netherwater.tasks.WaterAnimationAgent.run(WaterAnimationAgent.java:25) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.4.jar:git-Spigot-628435a-6917945]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.4.jar:git-Spigot-628435a-6917945]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1060) ~[spigot-1.16.4.jar:git-Spigot-628435a-6917945]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[spigot-1.16.4.jar:git-Spigot-628435a-6917945]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[spigot-1.16.4.jar:git-Spigot-628435a-6917945]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[spigot-1.16.4.jar:git-Spigot-628435a-6917945]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-628435a-6917945]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by ceskyDJ** [comment]
Its caused when the world is unloaded by Multiverse plugin (or something similar).
